### ISSUE TITLE
Could `blink_cursorline` take a argument to override config options for that specific invocation

### ISSUE THREAD

**Issue by IndianBoy42** [Grazfather/blinker.nvim#1]
I'm setting up some autocommands and I think I'll want automatic invocations to blink just once while manual invocations maybe more

**Comment by Grazfather** [comment]
Yes, good idea. Is that something you'd like to push a PR for? Note that this plugin is written in Fennel. Otherwise I can do it.

**Comment by IndianBoy42** [comment]
I'm not really familiar with fennel at all, sorry

**Comment by Grazfather** [comment]
Done in 0046ecd26dd184e2307ade1592de88a8060d049c
